# .github/workflows/pyarmor_license.yml
name: PyArmor-License
on:
  schedule:

    - cron: "30 18 * * *"  # 北京时间02:30
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:

    - uses: actions/checkout@v4



    - name: 安装PyArmor
      run: pip install pyarmor==9.0.7 --no-cache



    - name: 生成密钥
      run: |
        mkdir -p license
        pyarmor gen key -e 31

        

    - name: 提交更新
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add license/
        git commit -m "AutoUpdate: $(date +'%Y%m%d_%H%M%S')"
        git push
