name: Build and Commit License

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  generate-license:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # 重要！保证后续提交权限



    - name: Set up Python 3.10.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.8'



    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyarmor==9.0.7 pyinstaller===5.13.2



    - name: Configure and generate license
      run: |
        pyarmor cfg outer_keyname=Qmusic.lic
        pyarmor gen key -e 31



    - name: Commit generated files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        mkdir -p license  # 创建目录（如果不存在）
        mv Qmusic.lic *.lic license/  # 移动生成文件到license目录
        git add license/
        git commit -m "Update license files via GitHub Actions"
        git push
