name: Python3.10.8 License Automation
on:
  schedule:

    - cron: "30 18 * * *"  # 优化触发时间为UTC 18:30（北京时间02:30）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        persist-credentials: false  # 增强安全设置



    - name: Setup Python 3.10.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.8"  # 精确指定维护版本
        cache: 'pip'  # 启用依赖缓存加速



    - name: Create workspace
      run: |
        mkdir -p license
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV



    - name: Install tools
      run: |
        python -m pip install --no-cache-dir --upgrade pip
        pip install pyarmor==9.0.7 pyinstaller==5.13.2



    - name: Configure environment
      run: |
        pyarmor init --src . 
        pyarmor cfg outer_keyname=Qmusic.lic



    - name: Generate license
      run: pyarmor gen key -e 31 --output ./license/
      env:
        PYARMOR_HOME: ./license  # 指定配置文件存储路径



    - name: Commit artifacts
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git config --global user.name "always1ov"
        git config --global user.email "always1ov@github.actions"
        git add ./license/
        git commit -m "[Bot] Auto-generated license $(date +'%Y%m%d-%H%M%S')"
        git push origin main
