# .github/workflows/pyarmor_license.yml
name: PyArmor-License
on:
  schedule:

    - cron: "30 18 * * *"  # 北京时间02:30
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:

    - uses: actions/checkout@v4



    - name: Setup Python 3.10.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.8"  # 精确指定维护版本
        cache: 'pip'  # 启用依赖缓存加速



    - name: Create workspace
      run: |
        mkdir -p license
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV



    - name: Install tools
      run: |
        python -m pip install --no-cache-dir --upgrade pip
        pip install pyarmor==9.0.7 pyinstaller==5.13.2



    - name: Configure environment
      run: |
        pyarmor init --src . 
        pyarmor cfg outer_keyname=Qmusic.lic



    - name: Generate license
      run: pyarmor gen key -e 31 --output ./license/
      env:
        PYARMOR_HOME: ./license  # 指定配置文件存储路径

        

    - name: 提交更新
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add license/
        git commit -m "AutoUpdate: $(date +'%Y%m%d_%H%M%S')"
        git push
